name: Push repo updates to Telegram

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: send custom message
      uses: toshikidev/gh2tg-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          @${{ github.actor }} ${{ github.event.name }} new commit(s) to https://github.com/${{ github.repository }}}
          Commit message: ${{ github.event.commits[0].message }}
          Commit SHA: ${{ github.sha }}
